# ==============================================================================
# ESPHome Configuration for ESP32-S3 Development Board
# Author: Baptiste F
# Date: 2024-12-07
# Version: 1.0
# Description: Default configuration for ESP32-S3 DevKitC-1 board
#              with logging, WiFi, API, OTA, and Web Server enabled.
# ==============================================================================

esphome:
  name: board-esp32-s3
  friendly_name: board-esp32-s3
  # Basic ESPHome configuration with a unique device name.
  # The name is used to identify the device in Home Assistant.

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
  # ESP32-S3 hardware configuration.
  # Ensure you are using the correct board name for your device.

# Enable logging for debugging and monitoring ESP32-S3 operations.
logger:

# Enable API integration with Home Assistant.
api:
  encryption:
    key: "your-encryption-key"
  # Encryption key to secure communication with Home Assistant.
  # Change this key for better security if setting up multiple devices.

# Enable OTA updates to flash the firmware without a USB cable.
ota:
  - platform: esphome
    password: ""your-password"
  # Use a strong password to prevent unauthorized updates.

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Store sensitive information (e.g., WiFi SSID and password) in `secrets.yaml`.

  # Enable a fallback hotspot (access point) if WiFi connection fails.
  ap:
    ssid: "Board-Esp32-S3 Fallback Hotspot"
    password: "w1jguBHtjxSf"
  # The fallback hotspot allows direct connection to the device for reconfiguration.

# Enable a captive portal for easier connection to the fallback hotspot.
captive_portal:

# Enable a web server for monitoring and control via a browser.
web_server:
  port: 80  # Default port for web access
  # The web server provides a simple interface to monitor logs, view sensors, and control actuators.
