#Autor : Baptiste F
#Date : 04/12/2024

substitutions:
  name: esp8266_board_d1_mini           # Technical name of the device
  friendly_name: Board ESP8266 D1 Mini  # Friendly name displayed in the user interface

esphome:
  name: ${name}                         # Use the substitution for the technical name
  friendly_name: ${friendly_name}       # Use the substitution for the friendly name

esp8266:
  board: d1_mini                        # Specify the exact board model (D1 Mini)

# Enable logging for debugging and data inspection
logger:
  level: DEBUG                          # Logging level set to DEBUG for detailed information

# Enable Home Assistant integration via the API
api:
  encryption:
    key: "your-encryption-key"          # Add an encryption key to secure communication with Home Assistant

# Enable over-the-air (OTA) updates to flash firmware without a physical connection
ota:

# Wi-Fi configuration
wifi:
  ssid: !secret wifi_ssid           # Wi-Fi network name (protected using secrets.yaml)
  password: !secret wifi_password   # Wi-Fi password (protected using secrets.yaml)

  # Fallback access point if the Wi-Fi connection fails
  ap:
    ssid: "Fallback-Board-D1-Mini"      # Fallback Wi-Fi access point name
    password: "fallbackpassword"        # Fallback access point password

# Enable a web server to view and interact with the device
web_server:
  port: 80                              # Default port for the web server (can be changed if needed)

# Enable captive portal to manage Wi-Fi connection issues
captive_portal:
